# Generated by Django 3.1.2 on 2020-12-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filer',
            name='filing',
        ),
        migrations.AddField(
            model_name='filing',
            name='filers',
            field=models.ManyToManyField(to='form4.Filer'),
        ),
    ]
