# Generated by Django 3.1.2 on 2020-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0002_auto_20201215_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filer',
            name='cik',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
