# Generated by Django 3.1.2 on 2020-12-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0003_auto_20201215_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('symbol',)},
        ),
        migrations.AlterModelOptions(
            name='filer',
            options={'ordering': ('name',)},
        ),
    ]
