# Generated by Django 3.1.2 on 2020-12-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0004_auto_20201215_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filing',
            options={'ordering': ('date_filed',)},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('date',)},
        ),
    ]
