# Generated by Django 3.1.2 on 2020-12-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0005_auto_20201215_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cik',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
