# Generated by Django 3.1.2 on 2020-12-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0006_auto_20201215_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(choices=[('P', 'PURCHASED'), ('S', 'SOLD'), ('S-T', 'SOLD - TAX'), ('S-M', 'SOLD - MARGIN CALL'), ('A-B', 'ACQUIRED - 10b5-1'), ('A-P', 'ACQUIRED - PURCHASE PLAN'), ('A-I', 'ACQUIRED - INCENTIVE'), ('A-D', 'ACQUIRED - DIVIDEND REINVENTMENT')], max_length=3),
        ),
    ]
