# Generated by Django 3.1.2 on 2020-12-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0007_auto_20201225_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='best_filing_url',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filing',
            name='index_url',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(choices=[('P', 'BOUGHT'), ('S', 'SOLD'), ('A', 'ACQUIRED'), ('S-T', 'SOLD - TAX'), ('S-M', 'SOLD - MARGIN CALL'), ('A-B', 'ACQUIRED - 10b5-1'), ('A-P', 'ACQUIRED - PURCHASE PLAN'), ('A-I', 'ACQUIRED - COMPENSATION'), ('A-D', 'ACQUIRED - DIVIDEND')], max_length=3),
        ),
    ]
