# Generated by Django 3.1.2 on 2020-12-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0008_auto_20201225_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filing',
            old_name='best_filing_url',
            new_name='filing_url',
        ),
    ]
