# Generated by Django 3.1.2 on 2021-01-13 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0009_auto_20201225_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='code',
            field=models.CharField(choices=[('P', 'BOUGHT'), ('P-B', 'BOUGHT - 10b5-1'), ('S', 'SOLD'), ('S-B', 'SOLD - 10b5-1'), ('S-T', 'SOLD - TAX'), ('S-M', 'SOLD - MARGIN CALL'), ('A', 'ACQUIRED'), ('A-B', 'ACQUIRED - 10b5-1'), ('A-P', 'ACQUIRED - PURCHASE PLAN'), ('A-I', 'ACQUIRED - COMPENSATION'), ('A-D', 'ACQUIRED - DIVIDEND')], max_length=3),
        ),
        migrations.CreateModel(
            name='StockPriceOnDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form4.company')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='price_history',
            field=models.ManyToManyField(to='form4.StockPriceOnDay'),
        ),
    ]
