# Generated by Django 3.1.2 on 2021-01-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form4', '0010_auto_20210113_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='price_history',
        ),
        migrations.DeleteModel(
            name='StockPriceOnDay',
        ),
    ]
